version: '3.4'
services:
  apimysqldocker:
    image: posterr
    container_name: posterapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - database
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
      - SQL_CONNECTION_STRING=server=database; userid=mac;pwd=hw8vup5e;port=3306;database=productsdb;
      
  database:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: hw8vup5e
      MYSQL_USER: mac
      MYSQL_PASSWORD: hw8vup5e
      MYSQL_DATABASE: productsdb
      
volumes:
  db-volume: